[build]
publish = "public"
command = "hugo --gc --minify"

  [build.environment]
<<<<<<< HEAD
  HUGO_VERSION = "0.124.1"

[context.production.environment]
HUGO_VERSION = "0.124.1"
=======
  HUGO_VERSION = "0.128.1"

[context.production.environment]
HUGO_VERSION = "0.128.1"
>>>>>>> d479487 (Update netlify.toml with Hugo version 0.128.1)
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

  [context.split1.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

  [context.deploy-preview.environment]
<<<<<<< HEAD
  HUGO_VERSION = "0.124.1"
=======
  HUGO_VERSION = "0.128.1"
>>>>>>> d479487 (Update netlify.toml with Hugo version 0.128.1)

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/public/*"
to = "/public/"
status = 200
